import {
  Accessibility,
  AirVent,
  Baby,
  BookOpen,
  Briefcase,
  BriefcaseMedical,
  Bus,
  BusFront,
  ChefHat,
  CigaretteOff,
  Circle,
  Coffee,
  Croissant,
  Cross,
  CupSoda,
  Ear,
  Eye,
  GlassWater,
  Hamburger,
  Hand,
  HandHeart,
  HeartPlus,
  Hospital,
  House,
  HouseHeart,
  IceCreamCone,
  LampCeiling,
  Landmark,
  Logs,
  Martini,
  MegaphoneOff,
  MessageCircleHeart,
  Pill,
  Route,
  Ship,
  Shirt,
  Smartphone,
  SmartphoneNfc,
  Sofa,
  Soup,
  Speech,
  Stethoscope,
  Store,
  Theater,
  Toilet,
  TrainFront,
  TrainFrontTunnel,
  TramFront,
  Umbrella,
  Users,
  Utensils,
} from "lucide-react";

export default function Icon({ id, size }: { id: string; size: number }) {
  // TODO: Ideally, there would be a single configuration for all categories, criteria, etc. including
  //  their icons. This would require to add the icons to the backend config and share the config, e.g.
  //  through a package
  const icons: Record<string, typeof Utensils> = {
    // top-level categories
    "food-and-drinks": Utensils,
    "public-transport": BusFront,
    "health-care": Stethoscope,
    "social-care": Users,
    education: BookOpen,
    "government-buildings": Landmark,
    work: Briefcase,
    culture: Theater,
    "ways-crossings": Route,
    // sub-categories
    "drinking-water": GlassWater,
    "food-stores": Store,
    bakeries: Croissant,
    "ice-cream": IceCreamCone,
    restaurants: ChefHat,
    cafes: Coffee,
    canteen: Utensils,
    "fast-food": Hamburger,
    "food-court": Utensils,
    bars: Martini,
    "bus-platforms": Bus,
    "tram-platforms": TramFront,
    "subway-platforms": TrainFrontTunnel,
    "train-platforms": TrainFront,
    "ferry-platforms": Ship,
    "light-rail-platforms": TramFront,
    "light-rail-stations": TramFront,
    "bus-stations": Bus,
    "tram-stations": TramFront,
    "subway-stations": TrainFrontTunnel,
    "train-stations": TrainFront,
    "ferry-stations": Ship,
    "health-counselling": MessageCircleHeart,
    doctors: BriefcaseMedical,
    hospitals: Hospital,
    clinics: Hospital,
    pharmacies: Pill,
    therapists: HandHeart,
    "psycho-therapists": Speech,
    "other-health-facilities": HeartPlus,
    "health-shops": HouseHeart,
    "community-centers": House,
    "counselling-services": Speech,
    "ambulatory-services": Cross,
    "senior-facilities": Users,
    "child-youth-facilities": Baby,
    "disabled-facilities": Users,
    "refugee-accommodations": Users,
    "women-mother-shelters": Users,
    "queer-facilities": Users,
    "addiction-facilities": Users,
    "clothing-banks": Shirt,
    "charity-shops": HouseHeart,
    "soup-kitchens-food-banks": Soup,
    // criteria
    //// wheelchair
    "is-wheelchair-accessible": Accessibility,
    "has-wheelchair-accessible-toilet": Toilet,
    //// climate
    "smoking-is-prohibited": CigaretteOff,
    "has-air-conditioning": AirVent,
    //// toilet
    "has-toilet": Toilet,
    //// blind
    "is-accessible-to-visually-impaired": Eye,
    "has-tactile-paving": Logs,
    "has-information-board-with-speech-output": SmartphoneNfc,
    "has-tactile-writing": Hand,
    //// environment
    "has-quiet-hours": MegaphoneOff,
    //// deaf
    "is-accessible-to-hearing-impaired": Ear,
    "reservation-via-website": Smartphone,
    //// general
    "has-drinking-straws": CupSoda,
    "is-lit": LampCeiling,
    "has-shelter": Umbrella,
    "has-bench": Sofa,
    "has-website": Smartphone,
    "has-menu-on-website": Smartphone,
  };

  const Icon = icons[id] || Circle;

  return <Icon size={size} />;
}
